public enum UpgradeType
{
    DamagePercent,
    ExtraBullet,
    Penetration,
    AttackSpeed,
    Knockback,
    HomingMissileTurret,
    HomingMissileTurretCooldown,
    HomingMissileTurretDamagePercent,
    HomingMissileTurretExtraMissile,
    HomingMissileTurretShockwaveOnImpact,
    HomingMissileTurretMiniMissiles,
    LaserTurret,
    LaserTurretCooldown,
    LaserTurretDamagePercent,
    LaserTurretDuration,
    LaserTurretSweepingLaser,
    LaserTurretSideLaser,
    ShotgunTurret,
    ShotgunTurretCooldown,
    ShotgunTurretDamagePercent
}
